//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUFL.GUI.FLResultPresentationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="NUFL.GUI.Model", ConfigurationName="FLResultPresentationServiceReference.IFLResultPresenter")]
    public interface IFLResultPresenter {
        
        [System.ServiceModel.OperationContractAttribute(Action="NUFL.GUI.Model/IFLResultPresenter/Present", ReplyAction="NUFL.GUI.Model/IFLResultPresenter/PresentResponse")]
        void Present();
        
        [System.ServiceModel.OperationContractAttribute(Action="NUFL.GUI.Model/IFLResultPresenter/Present", ReplyAction="NUFL.GUI.Model/IFLResultPresenter/PresentResponse")]
        System.Threading.Tasks.Task PresentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFLResultPresenterChannel : NUFL.GUI.FLResultPresentationServiceReference.IFLResultPresenter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FLResultPresenterClient : System.ServiceModel.ClientBase<NUFL.GUI.FLResultPresentationServiceReference.IFLResultPresenter>, NUFL.GUI.FLResultPresentationServiceReference.IFLResultPresenter {
        
        public FLResultPresenterClient() {
        }
        
        public FLResultPresenterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FLResultPresenterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FLResultPresenterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FLResultPresenterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Present() {
            base.Channel.Present();
        }
        
        public System.Threading.Tasks.Task PresentAsync() {
            return base.Channel.PresentAsync();
        }
    }
}
